-- MySQL Script generated by MySQL Workbench
-- qua 04 out 2017 10:34:10 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `sexo` TINYINT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idUsuario`, `email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perqunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perqunta` (
  `idPergunta` INT NOT NULL,
  `enunciado` VARCHAR(200) NOT NULL,
  `opcao` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idPergunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meta` (
  `idMeta` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `categoria` VARCHAR(12) NOT NULL,
  `progresso` INT NULL,
  PRIMARY KEY (`idMeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Respostas` (
  `idUsuario` INT NOT NULL,
  `idPergunta` INT NOT NULL,
  `opcao` INT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idUsuario`, `idPergunta`),
  INDEX `fk_Usuario_has_Quest_Quest1_idx` (`idPergunta` ASC),
  INDEX `fk_Usuario_has_Quest_Usuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Quest_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Quest_Quest1`
    FOREIGN KEY (`idPergunta`)
    REFERENCES `mydb`.`Perqunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Progresso` (
  `Questoes_idQuest` INT NOT NULL,
  `Meta_idMeta` INT NOT NULL,
  `progresso` INT NULL,
  PRIMARY KEY (`Questoes_idQuest`, `Meta_idMeta`),
  INDEX `fk_Questoes_has_Meta_Meta1_idx` (`Meta_idMeta` ASC),
  INDEX `fk_Questoes_has_Meta_Questoes1_idx` (`Questoes_idQuest` ASC),
  CONSTRAINT `fk_Questoes_has_Meta_Questoes1`
    FOREIGN KEY (`Questoes_idQuest`)
    REFERENCES `mydb`.`Perqunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questoes_has_Meta_Meta1`
    FOREIGN KEY (`Meta_idMeta`)
    REFERENCES `mydb`.`Meta` (`idMeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  `nome` VARCHAR(70) NULL,
  `senha` VARCHAR(12) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin_has_Perqunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin_has_Perqunta` (
  `Admin_idAdmin` INT NOT NULL,
  `Perqunta_idPergunta` INT NOT NULL,
  PRIMARY KEY (`Admin_idAdmin`, `Perqunta_idPergunta`),
  INDEX `fk_Admin_has_Perqunta_Perqunta1_idx` (`Perqunta_idPergunta` ASC),
  INDEX `fk_Admin_has_Perqunta_Admin1_idx` (`Admin_idAdmin` ASC),
  CONSTRAINT `fk_Admin_has_Perqunta_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_has_Perqunta_Perqunta1`
    FOREIGN KEY (`Perqunta_idPergunta`)
    REFERENCES `mydb`.`Perqunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meta_has_Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meta_has_Admin` (
  `Meta_idMeta` INT NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`Meta_idMeta`, `Admin_idAdmin`),
  INDEX `fk_Meta_has_Admin_Admin1_idx` (`Admin_idAdmin` ASC),
  INDEX `fk_Meta_has_Admin_Meta1_idx` (`Meta_idMeta` ASC),
  CONSTRAINT `fk_Meta_has_Admin_Meta1`
    FOREIGN KEY (`Meta_idMeta`)
    REFERENCES `mydb`.`Meta` (`idMeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meta_has_Admin_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
